// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.0
// source: proto/coffeeshop.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type MenuRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MenuRequest) Reset() {
	*x = MenuRequest{}
	mi := &file_proto_coffeeshop_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MenuRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MenuRequest) ProtoMessage() {}

func (x *MenuRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_coffeeshop_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MenuRequest.ProtoReflect.Descriptor instead.
func (*MenuRequest) Descriptor() ([]byte, []int) {
	return file_proto_coffeeshop_proto_rawDescGZIP(), []int{0}
}

type Order struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Items         []*Item                `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Order) Reset() {
	*x = Order{}
	mi := &file_proto_coffeeshop_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Order) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Order) ProtoMessage() {}

func (x *Order) ProtoReflect() protoreflect.Message {
	mi := &file_proto_coffeeshop_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Order.ProtoReflect.Descriptor instead.
func (*Order) Descriptor() ([]byte, []int) {
	return file_proto_coffeeshop_proto_rawDescGZIP(), []int{1}
}

func (x *Order) GetItems() []*Item {
	if x != nil {
		return x.Items
	}
	return nil
}

type Receipt struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Receipt) Reset() {
	*x = Receipt{}
	mi := &file_proto_coffeeshop_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Receipt) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Receipt) ProtoMessage() {}

func (x *Receipt) ProtoReflect() protoreflect.Message {
	mi := &file_proto_coffeeshop_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Receipt.ProtoReflect.Descriptor instead.
func (*Receipt) Descriptor() ([]byte, []int) {
	return file_proto_coffeeshop_proto_rawDescGZIP(), []int{2}
}

func (x *Receipt) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type OrderStatus struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OrderId       string                 `protobuf:"bytes,1,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	Status        string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OrderStatus) Reset() {
	*x = OrderStatus{}
	mi := &file_proto_coffeeshop_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OrderStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrderStatus) ProtoMessage() {}

func (x *OrderStatus) ProtoReflect() protoreflect.Message {
	mi := &file_proto_coffeeshop_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrderStatus.ProtoReflect.Descriptor instead.
func (*OrderStatus) Descriptor() ([]byte, []int) {
	return file_proto_coffeeshop_proto_rawDescGZIP(), []int{3}
}

func (x *OrderStatus) GetOrderId() string {
	if x != nil {
		return x.OrderId
	}
	return ""
}

func (x *OrderStatus) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type Menu struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Items         []*Item                `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Menu) Reset() {
	*x = Menu{}
	mi := &file_proto_coffeeshop_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Menu) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Menu) ProtoMessage() {}

func (x *Menu) ProtoReflect() protoreflect.Message {
	mi := &file_proto_coffeeshop_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Menu.ProtoReflect.Descriptor instead.
func (*Menu) Descriptor() ([]byte, []int) {
	return file_proto_coffeeshop_proto_rawDescGZIP(), []int{4}
}

func (x *Menu) GetItems() []*Item {
	if x != nil {
		return x.Items
	}
	return nil
}

type Item struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Description   string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	Price         float64                `protobuf:"fixed64,4,opt,name=price,proto3" json:"price,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Item) Reset() {
	*x = Item{}
	mi := &file_proto_coffeeshop_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Item) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Item) ProtoMessage() {}

func (x *Item) ProtoReflect() protoreflect.Message {
	mi := &file_proto_coffeeshop_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Item.ProtoReflect.Descriptor instead.
func (*Item) Descriptor() ([]byte, []int) {
	return file_proto_coffeeshop_proto_rawDescGZIP(), []int{5}
}

func (x *Item) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Item) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Item) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Item) GetPrice() float64 {
	if x != nil {
		return x.Price
	}
	return 0
}

type CoffeeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ItemName      string                 `protobuf:"bytes,1,opt,name=item_name,json=itemName,proto3" json:"item_name,omitempty"`
	Size          string                 `protobuf:"bytes,2,opt,name=size,proto3" json:"size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CoffeeRequest) Reset() {
	*x = CoffeeRequest{}
	mi := &file_proto_coffeeshop_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CoffeeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CoffeeRequest) ProtoMessage() {}

func (x *CoffeeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_coffeeshop_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CoffeeRequest.ProtoReflect.Descriptor instead.
func (*CoffeeRequest) Descriptor() ([]byte, []int) {
	return file_proto_coffeeshop_proto_rawDescGZIP(), []int{6}
}

func (x *CoffeeRequest) GetItemName() string {
	if x != nil {
		return x.ItemName
	}
	return ""
}

func (x *CoffeeRequest) GetSize() string {
	if x != nil {
		return x.Size
	}
	return ""
}

type Coffee struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ItemName      string                 `protobuf:"bytes,1,opt,name=item_name,json=itemName,proto3" json:"item_name,omitempty"`
	Size          string                 `protobuf:"bytes,2,opt,name=size,proto3" json:"size,omitempty"`
	Status        string                 `protobuf:"bytes,3,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Coffee) Reset() {
	*x = Coffee{}
	mi := &file_proto_coffeeshop_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Coffee) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Coffee) ProtoMessage() {}

func (x *Coffee) ProtoReflect() protoreflect.Message {
	mi := &file_proto_coffeeshop_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Coffee.ProtoReflect.Descriptor instead.
func (*Coffee) Descriptor() ([]byte, []int) {
	return file_proto_coffeeshop_proto_rawDescGZIP(), []int{7}
}

func (x *Coffee) GetItemName() string {
	if x != nil {
		return x.ItemName
	}
	return ""
}

func (x *Coffee) GetSize() string {
	if x != nil {
		return x.Size
	}
	return ""
}

func (x *Coffee) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

var File_proto_coffeeshop_proto protoreflect.FileDescriptor

const file_proto_coffeeshop_proto_rawDesc = "" +
	"\n" +
	"\x16proto/coffeeshop.proto\x12\n" +
	"coffeeshop\"\r\n" +
	"\vMenuRequest\"/\n" +
	"\x05Order\x12&\n" +
	"\x05items\x18\x01 \x03(\v2\x10.coffeeshop.ItemR\x05items\"\x19\n" +
	"\aReceipt\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"@\n" +
	"\vOrderStatus\x12\x19\n" +
	"\border_id\x18\x01 \x01(\tR\aorderId\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\".\n" +
	"\x04Menu\x12&\n" +
	"\x05items\x18\x01 \x03(\v2\x10.coffeeshop.ItemR\x05items\"b\n" +
	"\x04Item\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12\x14\n" +
	"\x05price\x18\x04 \x01(\x01R\x05price\"@\n" +
	"\rCoffeeRequest\x12\x1b\n" +
	"\titem_name\x18\x01 \x01(\tR\bitemName\x12\x12\n" +
	"\x04size\x18\x02 \x01(\tR\x04size\"Q\n" +
	"\x06Coffee\x12\x1b\n" +
	"\titem_name\x18\x01 \x01(\tR\bitemName\x12\x12\n" +
	"\x04size\x18\x02 \x01(\tR\x04size\x12\x16\n" +
	"\x06status\x18\x03 \x01(\tR\x06status2\xff\x01\n" +
	"\n" +
	"CoffeeShop\x128\n" +
	"\aGetMenu\x12\x17.coffeeshop.MenuRequest\x1a\x10.coffeeshop.Menu\"\x000\x01\x12=\n" +
	"\n" +
	"MakeCoffee\x12\x19.coffeeshop.CoffeeRequest\x1a\x12.coffeeshop.Coffee\"\x00\x126\n" +
	"\n" +
	"PlaceOrder\x12\x11.coffeeshop.Order\x1a\x13.coffeeshop.Receipt\"\x00\x12@\n" +
	"\x0eGetOrderStatus\x12\x13.coffeeshop.Receipt\x1a\x17.coffeeshop.OrderStatus\"\x00B\x1cZ\x1agrpc_starbuckscoffee/protob\x06proto3"

var (
	file_proto_coffeeshop_proto_rawDescOnce sync.Once
	file_proto_coffeeshop_proto_rawDescData []byte
)

func file_proto_coffeeshop_proto_rawDescGZIP() []byte {
	file_proto_coffeeshop_proto_rawDescOnce.Do(func() {
		file_proto_coffeeshop_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_coffeeshop_proto_rawDesc), len(file_proto_coffeeshop_proto_rawDesc)))
	})
	return file_proto_coffeeshop_proto_rawDescData
}

var file_proto_coffeeshop_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_proto_coffeeshop_proto_goTypes = []any{
	(*MenuRequest)(nil),   // 0: coffeeshop.MenuRequest
	(*Order)(nil),         // 1: coffeeshop.Order
	(*Receipt)(nil),       // 2: coffeeshop.Receipt
	(*OrderStatus)(nil),   // 3: coffeeshop.OrderStatus
	(*Menu)(nil),          // 4: coffeeshop.Menu
	(*Item)(nil),          // 5: coffeeshop.Item
	(*CoffeeRequest)(nil), // 6: coffeeshop.CoffeeRequest
	(*Coffee)(nil),        // 7: coffeeshop.Coffee
}
var file_proto_coffeeshop_proto_depIdxs = []int32{
	5, // 0: coffeeshop.Order.items:type_name -> coffeeshop.Item
	5, // 1: coffeeshop.Menu.items:type_name -> coffeeshop.Item
	0, // 2: coffeeshop.CoffeeShop.GetMenu:input_type -> coffeeshop.MenuRequest
	6, // 3: coffeeshop.CoffeeShop.MakeCoffee:input_type -> coffeeshop.CoffeeRequest
	1, // 4: coffeeshop.CoffeeShop.PlaceOrder:input_type -> coffeeshop.Order
	2, // 5: coffeeshop.CoffeeShop.GetOrderStatus:input_type -> coffeeshop.Receipt
	4, // 6: coffeeshop.CoffeeShop.GetMenu:output_type -> coffeeshop.Menu
	7, // 7: coffeeshop.CoffeeShop.MakeCoffee:output_type -> coffeeshop.Coffee
	2, // 8: coffeeshop.CoffeeShop.PlaceOrder:output_type -> coffeeshop.Receipt
	3, // 9: coffeeshop.CoffeeShop.GetOrderStatus:output_type -> coffeeshop.OrderStatus
	6, // [6:10] is the sub-list for method output_type
	2, // [2:6] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_proto_coffeeshop_proto_init() }
func file_proto_coffeeshop_proto_init() {
	if File_proto_coffeeshop_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_coffeeshop_proto_rawDesc), len(file_proto_coffeeshop_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_coffeeshop_proto_goTypes,
		DependencyIndexes: file_proto_coffeeshop_proto_depIdxs,
		MessageInfos:      file_proto_coffeeshop_proto_msgTypes,
	}.Build()
	File_proto_coffeeshop_proto = out.File
	file_proto_coffeeshop_proto_goTypes = nil
	file_proto_coffeeshop_proto_depIdxs = nil
}
